apiVersion: v1
kind: Namespace
metadata:
  name: development

---

apiVersion: v1
kind: Pod
metadata:
  name: namespacepod
  namespace: development
spec:
  containers:
  - name: namespacecontainer
    image: nginx:latest
    ports:
      - containerPort: 80