apiVersion: v1
kind: Service
metadata:
  name: MYAPP
  namespace: default
spec:
  selector:
    app: MYAPP
  type: ClusterIP
  ports:
  - name: MYAPP
    protocol: TCP
    port: 3000
    targetPort: 5000 