apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment
  labels:
    app: httpd
spec:
  replicas: 5
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      nodeSelector:
        kubernetes.io/hostname: minikube-m02
      containers:
      - name: httpd
        image: httpd
        ports:
        - containerPort: 80
