apiVersion: v1
kind: Pod
metadata:
  name: args-commands
  labels:
    app: args-commands
spec:
  containers:
  - name: args-commands
    image: balaban/entrypoint-cmd
    command: ["sleep"]  # This overwrites ENTRYPOINT in Dockerfile. 
    args: ["10"]  # This overwrites CMD in Dockerfile
    env:
    - name: firstkey
      value: "firstvalue"
    - name: secondkey
      value: "secondvalue"