apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: default
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: mypvc    
      containers:
      - name: mysql
        image: mysql:5.7
        envFrom:
          - secretRef:
              name: mysqlsecret
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: /var/lib/mysql
            name: pv-storage