apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi