apiVersion: apps/v1
kind: Deployment
metadata:
  name:  frontend-deployment
  namespace: default
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: result-server
      tier: frontend
  replicas: 2
  template:
    metadata:
      labels:
        app:  result-server
        tier: frontend
    spec:
      containers:
      - name: result-server
        image: balaban/result-server
        envFrom:
          - secretRef:
              name: appsecret
        env:
          - name: MYSQL_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: server-config
                key: MYSQL_DATABASE_HOST
        ports:
        - containerPort: 80