apiVersion: v1
kind: Service
metadata:
  name: resultserver-service
  namespace: default
  labels:
    team: devops
spec:
  selector:
    app:  result-server
    tier: frontend
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30002