apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-deployment
  namespace: default
  labels:
    team: devops
spec:
  selector:
    matchLabels:
      app: web-server
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app:  web-server
        tier: backend
    spec:
      containers:
      - name: web-server
        image: balaban/web-server
        envFrom:
          - secretRef:
              name: appsecret
        env:
          - name: MYSQL_DATABASE_HOST
            valueFrom:
              configMapKeyRef:
                name: server-config
                key: MYSQL_DATABASE_HOST
        ports:
        - containerPort: 80
