apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-2
  namespace: resources-limits
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: quota-mem-cpu-2
    resources:
      limits:
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"