apiVersion: v1
kind: Pod
metadata:
  name: default-memory
  namespace: resources-limits
spec:
  containers:
  - name: default-memory
    image: nginx
    resources:
      requests:
        memory: "128Mi"