apiVersion: v1
kind: ResourceQuota
metadata:
  name: object-quota
  namespace: resources-limits
spec:
  hard:
    pods: "2"
    services.nodeports: "1"
    services.loadbalancers: "0"
    persistentvolumeclaims: "2"
    