apiVersion: v1
kind: Service   
metadata:
  namespace: resources-limits
  name: quota-service
  labels:
    app: quota-service
spec:
  type: NodePort
  ports:
  - port: 80  
    targetPort: 80
  selector:
    purpose: quota-demo