apiVersion: apps/v1
kind: Deployment
metadata:  
  namespace: resources-limits
  name: pod-quota
spec:
  selector:
    matchLabels:
      purpose: quota-demo
  replicas: 3
  template:
    metadata:
      labels:
        purpose: quota-demo
    spec:
      containers:
      - name: pod-quota
        image: nginx