apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
  namespace: demo  
spec:
  type: NodePort  
  ports:
  - port: 3000  
    targetPort: 5000
    nodePort: 30036
  selector:
    app: web-flask