apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-project
  namespace: default

---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: sa-csr
subjects:
- kind: ServiceAccount
  name: sa-project # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io

--- 

apiVersion: v1
kind: Pod
metadata:
  name: pod-sa
  namespace: default
spec:
  serviceAccountName: sa-project
  containers:
  - name: projecontainer
    image: ozgurozturknet/k8s:latest
    ports:
    - containerPort: 80

