apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: redis
    volumeMounts:
    - name: myvolume
      mountPath: "/etc/foo"
      readOnly: true
  volumes:
  - name: myvolume
    secret:
      secretName: mysecret