apiVersion: v1
kind: Pod
metadata:
  name: test
  labels:
    app : web-nginx
spec:
  containers:
  - image: nginx:latest
    ports:
    - containerPort: 80
    name: test
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: vol-dyn
  volumes:
  - name: vol-dyn
    persistentVolumeClaim:
      claimName: myclaim