apiVersion: v1
kind: Pod
metadata:
  name: firstpod
  labels:
    app: frontend
    team: developer
spec:
  containers:
    - name: ng
      image: nginx:latest
      ports:
        - containerPort: 80