apiVersion: v1
kind: Pod
metadata:
  name: two-containers
  labels:
    app: two-container
spec:
  restartPolicy: Never
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: nginx-container
    image: nginx
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: sidecar-container
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ["/bin/sh"]
    args: ['-c', 'echo "Hello from the debian container" > /pod-data/index.html && sleep 600']
---
apiVersion: v1
kind: Service   
metadata:
  name: two-containers-svc
spec:
  type: NodePort 
  ports:
  - port: 80 
    targetPort: 80
    nodePort: 30001
  selector:
    app: two-container
