apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: firstdeployment
  name: firstdeployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: firstdeployment
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: firstdeployment
    spec:
      containers:
      - image: nginx
        name: nginx
        ports:
        - containerPort: 80
        resources: {}
status: {}
