apiVersion: v1
kind: Pod
metadata:
  name: multicontainer
spec:
  containers:
    - name: webcontainer
      image: nginx
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: sharedvolume
    - name: sidecarcontainer
      image: busybox
      command: ["/bin/sh"]
      args: ["-c", "while true; do wget -O /var/log/index.html https://raw.githubusercontent.com/balaban1432/k8s/main/index.html; sleep 15; done"]
      volumeMounts:
        - mountPath: /var/log
          name: sharedvolume
  volumes:
    - name: sharedvolume
      emptyDir: {}
        
            

